services:
  - type: web
    name: trade90-staging-rdcxqg
    runtime: python
    plan: free
    region: singapore
    buildCommand: bash render-build.sh
    startCommand: gunicorn trade90.wsgi:application --bind 0.0.0.0:$PORT --access-logfile -
    healthCheckPath: /health/
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: trade90.settings.production
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: DJANGO_SUPERUSER_USERNAME
        value: trade90-admin
      - key: DJANGO_SUPERUSER_PASSWORD
        generateValue: true
